<a href="https://colab.research.google.com/github/Raghibshams/CREDIT-CARD-FRAUD-DETECTIONs/blob/master/Participated_in_HackerEarth_Machine_Learning_challenge_Calculate_the_severity_of_an_airplane_accident.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
df = pd.read_csv('train.csv')
df1=pd.read_csv('test.csv')

In [5]:
df

Severity  ...  Accident_ID
0                   Minor_Damage_And_Injuries  ...         7570
1                   Minor_Damage_And_Injuries  ...        12128
2           Significant_Damage_And_Fatalities  ...         2181
3     Significant_Damage_And_Serious_Injuries  ...         5946
4           Significant_Damage_And_Fatalities  ...         9054
...                                       ...  ...          ...
9995  Significant_Damage_And_Serious_Injuries  ...        11493
9996                Highly_Fatal_And_Damaging  ...          305
9997  Significant_Damage_And_Serious_Injuries  ...          612
9998                Minor_Damage_And_Injuries  ...         4963
9999                Highly_Fatal_And_Damaging  ...         9387

[10000 rows x 12 columns]

In [6]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

Safety_Score                  21.917808
Days_Since_Inspection          4.000000
Total_Safety_Complaints        7.000000
Control_Metric                16.408387
Turbulence_In_gforces          0.157681
Cabin_Temperature              3.600000
Accident_Type_Code             3.000000
Max_Elevation              12623.004605
Violations                     2.000000
Adverse_Weather_Metric         0.341996
Accident_ID                 6251.750000
dtype: float64


In [7]:
Q1 = df1.quantile(0.25)
Q3 = df1.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

Safety_Score                  22.157534
Days_Since_Inspection          4.000000
Total_Safety_Complaints        8.000000
Control_Metric                15.417046
Turbulence_In_gforces          0.149116
Cabin_Temperature              3.600000
Accident_Type_Code             3.000000
Max_Elevation              12750.667354
Violations                     2.000000
Adverse_Weather_Metric         0.302271
Accident_ID                 6237.500000
dtype: float64


In [8]:
df = df[~((df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))).any(axis=1)]
df.shape

(7929, 12)

In [9]:
df1

Safety_Score  Days_Since_Inspection  ...  Adverse_Weather_Metric  Accident_ID
0        19.497717                     16  ...                0.069692            1
1        58.173516                     15  ...                0.002777           10
2        33.287671                     15  ...                0.004316           14
3         3.287671                     21  ...                0.199990           17
4        10.867580                     18  ...                0.483696           21
...            ...                    ...  ...                     ...          ...
2495     68.127854                      8  ...                0.659387        12484
2496     54.840183                      9  ...                0.005010        12487
2497     36.712329                     14  ...                0.008629        12488
2498     38.721461                     13  ...                0.006247        12491
2499     36.073059                     11  ...                0.024409        12493

[2500 rows x 11 columns]

In [0]:
from sklearn.model_selection import train_test_split


In [0]:
from sklearn import preprocessing
x=df.drop("Severity",axis=1)




y= df.Severity.values.astype(object)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1)

In [53]:
X_train

Safety_Score  Days_Since_Inspection  ...  Adverse_Weather_Metric  Accident_ID
8410     46.255708                     15  ...                0.060060         3570
6155     40.045662                     13  ...                0.018465         2723
368      34.109589                     15  ...                0.007183        11484
8462     21.917808                     18  ...                0.234735         6339
5213     20.958904                     15  ...                0.100580        11645
...            ...                    ...  ...                     ...          ...
9185     42.968037                     16  ...                0.101520         7967
7423     31.324201                     15  ...                0.006082         7297
3200     27.853881                     13  ...                0.065318        10441
1160     19.680365                     16  ...                0.488383         8261
9600     34.657534                     11  ...                0.060784        12281

[7136 rows x 11 columns]

In [54]:
y_train

array(['Minor_Damage_And_Injuries',
       'Significant_Damage_And_Serious_Injuries',
       'Significant_Damage_And_Serious_Injuries', ...,
       'Highly_Fatal_And_Damaging', 'Highly_Fatal_And_Damaging',
       'Highly_Fatal_And_Damaging'], dtype=object)

In [0]:
y_train = y_train.astype(object)

In [56]:


print("Dimension of Train set",X_train.shape)
#print("Dimension of Test set",X_test.shape,"\n")


from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()


encoder.fit(y_train)
Y_train = encoder.transform(y_train)

# encoding test labels 
encoder.fit(y_test)
Y_test = encoder.transform(y_test)

#Total Number of Continous and Categorical features in the training set

#list(set(X_train.columns) - set(num_cols))




# Scaling the Train and Test feature set 


Dimension of Train set (7136, 11)


In [57]:

len(Y_train)

7136

In [58]:
X_train.shape

(7136, 11)

In [0]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.metrics import confusion_matrix,classification_report

In [0]:
params_grid = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]


In [0]:

from sklearn import tree
from sklearn import decomposition, datasets
sc = StandardScaler()
pca = decomposition.PCA()
decisiontree = tree.DecisionTreeClassifier()
from sklearn import decomposition, datasets
from sklearn.pipeline import Pipeline
pipe = Pipeline(steps=[('sc', sc),
                           ('pca', pca),
                           ('decisiontree', decisiontree)])
n_components = list(range(1,x.shape[1]+1,1))
criterion = ['gini', 'entropy']
max_depth = [4,6,8,12,56,500]
parameters = dict(pca__n_components=n_components,
                      decisiontree__criterion=criterion,
                      decisiontree__max_depth=max_depth)

clf = GridSearchCV(pipe, parameters)

In [0]:
model = tree.DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=56, max_features=None, max_leaf_nodes=400,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [72]:
clf.fit(X_train, Y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('sc',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('pca',
                                        PCA(copy=True, iterated_power='auto',
                                            n_components=None,
                                            random_state=None,
                                            svd_solver='auto', tol=0.0,
                                            whiten=False)),
                                       ('decisiontree',
                                        DecisionTreeClassifier(ccp_alpha=0.0,
                                                               class_weight=None,
                                                              

In [73]:
print('Best Criterion:', clf.best_estimator_.get_params()['decisiontree__criterion'])
print('Best max_depth:', clf.best_estimator_.get_params()['decisiontree__max_depth'])
print('Best Number Of Components:', clf.best_estimator_.get_params()['pca__n_components'])
print(); print(clf.best_estimator_.get_params()['decisiontree'])


Best Criterion: entropy
Best max_depth: 500
Best Number Of Components: 11

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=500, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')


In [0]:
y_predict = clf.predict(X_test)

In [75]:
y_predict

array([1, 0, 3, 0, 2, 0, 2, 2, 0, 3, 1, 1, 2, 2, 0, 1, 2, 0, 2, 1, 2, 3,
       0, 1, 0, 3, 1, 3, 0, 0, 1, 0, 0, 2, 3, 2, 3, 3, 3, 0, 3, 3, 3, 1,
       1, 0, 0, 1, 3, 3, 3, 3, 0, 1, 0, 2, 1, 0, 1, 2, 0, 2, 3, 2, 0, 0,
       3, 0, 3, 1, 2, 3, 1, 2, 1, 1, 3, 3, 0, 2, 1, 3, 0, 2, 3, 0, 0, 0,
       2, 1, 2, 3, 3, 3, 0, 1, 1, 1, 0, 3, 1, 0, 0, 0, 2, 3, 3, 2, 3, 3,
       1, 1, 0, 1, 1, 0, 3, 3, 0, 1, 1, 0, 3, 3, 0, 0, 3, 0, 0, 0, 3, 3,
       0, 3, 0, 2, 0, 0, 3, 1, 0, 0, 1, 3, 1, 1, 1, 0, 3, 2, 1, 3, 3, 1,
       1, 1, 3, 2, 1, 3, 3, 0, 3, 0, 2, 3, 0, 2, 0, 2, 3, 0, 0, 1, 2, 1,
       0, 2, 1, 1, 3, 3, 2, 2, 0, 3, 0, 0, 3, 0, 2, 3, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 3, 3, 3, 2, 3, 0, 1, 3, 3, 1, 3, 2, 2, 1, 2, 2, 0,
       0, 3, 0, 2, 3, 1, 0, 3, 3, 0, 1, 3, 0, 2, 1, 2, 0, 0, 0, 3, 0, 1,
       1, 1, 3, 3, 3, 3, 2, 0, 1, 1, 0, 1, 0, 1, 0, 1, 2, 0, 2, 3, 0, 1,
       0, 1, 0, 1, 3, 0, 3, 0, 0, 1, 1, 0, 2, 1, 3, 3, 0, 0, 3, 1, 0, 1,
       1, 0, 2, 1, 0, 1, 0, 1, 1, 3, 1, 1, 2, 1, 1,

In [76]:
Y_test

array([3, 0, 3, 0, 2, 0, 2, 2, 0, 3, 1, 1, 2, 2, 0, 3, 2, 0, 2, 1, 2, 3,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 2, 3, 2, 3, 3, 3, 0, 0, 3, 3, 1,
       1, 0, 0, 1, 3, 3, 3, 1, 0, 1, 0, 2, 1, 3, 1, 2, 3, 2, 3, 0, 0, 0,
       3, 0, 3, 1, 2, 3, 1, 2, 1, 1, 3, 3, 0, 2, 1, 3, 0, 2, 3, 0, 0, 0,
       2, 1, 2, 3, 3, 3, 0, 3, 1, 1, 3, 3, 1, 3, 0, 0, 2, 3, 3, 0, 3, 3,
       1, 3, 0, 0, 1, 0, 3, 3, 0, 1, 0, 0, 3, 3, 0, 0, 3, 0, 0, 0, 3, 3,
       0, 3, 3, 2, 2, 0, 3, 3, 0, 0, 1, 3, 1, 1, 1, 0, 3, 2, 1, 3, 1, 1,
       1, 1, 3, 2, 1, 3, 3, 2, 3, 0, 2, 3, 1, 2, 0, 2, 3, 0, 0, 1, 2, 2,
       0, 2, 1, 1, 1, 3, 0, 2, 0, 2, 0, 0, 3, 1, 2, 3, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 3, 0, 3, 3, 3, 3, 0, 0, 3, 3, 1, 3, 2, 2, 1, 2, 2, 0,
       0, 3, 0, 2, 3, 1, 0, 3, 3, 0, 3, 1, 0, 2, 3, 2, 0, 0, 0, 3, 0, 1,
       1, 1, 3, 3, 3, 3, 2, 0, 0, 2, 0, 1, 0, 3, 0, 1, 2, 0, 0, 3, 0, 1,
       1, 1, 0, 1, 3, 2, 3, 0, 2, 1, 1, 2, 2, 1, 3, 1, 1, 0, 3, 3, 0, 1,
       1, 0, 2, 1, 0, 3, 0, 0, 1, 3, 1, 0, 2, 1, 1,

In [0]:
from sklearn.metrics import accuracy_score

In [78]:

accuracy_score(Y_test, y_predict)

0.8259773013871374

In [0]:
test = pd.read_csv('test.csv')

In [80]:
test

Safety_Score  Days_Since_Inspection  ...  Adverse_Weather_Metric  Accident_ID
0        19.497717                     16  ...                0.069692            1
1        58.173516                     15  ...                0.002777           10
2        33.287671                     15  ...                0.004316           14
3         3.287671                     21  ...                0.199990           17
4        10.867580                     18  ...                0.483696           21
...            ...                    ...  ...                     ...          ...
2495     68.127854                      8  ...                0.659387        12484
2496     54.840183                      9  ...                0.005010        12487
2497     36.712329                     14  ...                0.008629        12488
2498     38.721461                     13  ...                0.006247        12491
2499     36.073059                     11  ...                0.024409        12493

[2500 rows x 11 columns]

In [0]:
y_predict1 = clf.predict(test)

In [82]:
y_predict1

array([0, 2, 1, ..., 3, 3, 0])

In [0]:
s = pd.read_csv('sample_submission.csv')

In [84]:
s

Accident_ID                                 Severity
0            1                Minor_Damage_And_Injuries
1           10                Highly_Fatal_And_Damaging
2           14                Highly_Fatal_And_Damaging
3           17  Significant_Damage_And_Serious_Injuries
4           21                Minor_Damage_And_Injuries
5           40                Highly_Fatal_And_Damaging
6           45                Highly_Fatal_And_Damaging
7           50        Significant_Damage_And_Fatalities
8           52                Highly_Fatal_And_Damaging
9           85                Minor_Damage_And_Injuries

In [0]:
t=test.Accident_ID

In [0]:
re= pd.DataFrame()

In [0]:
re['Accident_ID']  = t

In [0]:
re['Severity']  = y_predict1

In [89]:
re

Accident_ID  Severity
0               1         0
1              10         2
2              14         1
3              17         0
4              21         0
...           ...       ...
2495        12484         0
2496        12487         3
2497        12488         3
2498        12491         3
2499        12493         0

[2500 rows x 2 columns]

In [0]:
def score_to_numeric(x):
  if x==0:
    return "Highly_Fatal_And_Damaging"
  if x==1:
    return  'Minor_Damage_And_Injuries'
  if x==2:
    return  'Significant_Damage_And_Fatalities'
  if x==3:
    return  'Significant_Damage_And_Serious_Injuries'



In [91]:
re['Severity'] = re['Severity'].apply(score_to_numeric)
re

Accident_ID                                 Severity
0               1                Highly_Fatal_And_Damaging
1              10        Significant_Damage_And_Fatalities
2              14                Minor_Damage_And_Injuries
3              17                Highly_Fatal_And_Damaging
4              21                Highly_Fatal_And_Damaging
...           ...                                      ...
2495        12484                Highly_Fatal_And_Damaging
2496        12487  Significant_Damage_And_Serious_Injuries
2497        12488  Significant_Damage_And_Serious_Injuries
2498        12491  Significant_Damage_And_Serious_Injuries
2499        12493                Highly_Fatal_And_Damaging

[2500 rows x 2 columns]

In [92]:
set(y_train)

{'Highly_Fatal_And_Damaging',
 'Minor_Damage_And_Injuries',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries'}

In [93]:
Y_train

array([1, 3, 3, ..., 0, 0, 0])

In [94]:
y_train

array(['Minor_Damage_And_Injuries',
       'Significant_Damage_And_Serious_Injuries',
       'Significant_Damage_And_Serious_Injuries', ...,
       'Highly_Fatal_And_Damaging', 'Highly_Fatal_And_Damaging',
       'Highly_Fatal_And_Damaging'], dtype=object)

In [0]:
re.to_csv('file8.csv',index=False) 

In [96]:
s

Accident_ID                                 Severity
0            1                Minor_Damage_And_Injuries
1           10                Highly_Fatal_And_Damaging
2           14                Highly_Fatal_And_Damaging
3           17  Significant_Damage_And_Serious_Injuries
4           21                Minor_Damage_And_Injuries
5           40                Highly_Fatal_And_Damaging
6           45                Highly_Fatal_And_Damaging
7           50        Significant_Damage_And_Fatalities
8           52                Highly_Fatal_And_Damaging
9           85                Minor_Damage_And_Injuries

In [97]:
re

Accident_ID                                 Severity
0               1                Highly_Fatal_And_Damaging
1              10        Significant_Damage_And_Fatalities
2              14                Minor_Damage_And_Injuries
3              17                Highly_Fatal_And_Damaging
4              21                Highly_Fatal_And_Damaging
...           ...                                      ...
2495        12484                Highly_Fatal_And_Damaging
2496        12487  Significant_Damage_And_Serious_Injuries
2497        12488  Significant_Damage_And_Serious_Injuries
2498        12491  Significant_Damage_And_Serious_Injuries
2499        12493                Highly_Fatal_And_Damaging

[2500 rows x 2 columns]